# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: admin4j-parent deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: install admin4j-dependencies
        run: mvn clean && mvn clean install -Dmaven.test.skip=true --file admin4j-dependencies/pom.xml
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: deploy framework
        run: mvn install -Dmaven.test.skip=true -N --file ./pom.xml
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: deploy admin4j-parent
        run: mvn install deploy -Possrh -Dmaven.test.skip=true --file admin4j-parent/pom.xml
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: deploy spring-boot-parent
        run: mvn clean install deploy -Possrh  -Dmaven.test.skip=true --file spring-boot-parent/pom.xml
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}

#      - name: deploy admin4j framework
#        run: mvn clean install deploy -Dmaven.test.skip=true --file admin4j-common/pom.xml &&
#          mvn clean install deploy -Dmaven.test.skip=true --file admin4j-common-spring/pom.xml
#          mvn clean install deploy -Dmaven.test.skip=true --file admin4j-common-spring-web/pom.xml
#          mvn clean install deploy -Dmaven.test.skip=true --file log-spring-boot-starter/pom.xml
#          mvn clean install deploy -Dmaven.test.skip=true --file test-spring-boot-starter/pom.xml
#          mvn clean install deploy -Dmaven.test.skip=true --file web-spring-boot-starter/pom.xml
#        env:
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#          GITHUB_TOKEN: ${{ github.token }}
